version: '3'

services:

    nginx:
        build:
            context: ../..
            dockerfile: docker/images/nginx/Dockerfile
        container_name: web-nginx
        links:
            - php:php-fpm
        ports:
            - 8080:80
