#!/bin/sh

cd "$(dirname "$(command -v "$0")")" || exit 1

root_dir="$(realpath "$PWD/..")"

cd "$root_dir" || exit 1

eval "$(docker_bin/print_vars)"

docker_bin/check_conf || exit 1

docker-compose exec php composer "$@"
